language: python
matrix:
  include:
    - name: "Python 2.7 on Bionic"
      python: 2.7
      dist: bionic
    - name: "Python 3.8 on Bionic"
      python: 3.8
      dist: bionic
    - name: "Python 3.7 on Bionic"
      python: 3.7
      dist: bionic
    - name: "Python 3.6 on Bionic"
      python: 3.6
      dist: bionic
    - name: "Python 3.5 on Xenial"
      python: 3.5
      dist: xenial
    - name: "Python 3.4 on Xenial"
      python: 3.4
      dist: xenial

install: "pip install -r requirements-dev.txt"
script: "nose2"
